name: calculator_app
description: Technical Interview for Senior Flutter Engineer
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.0
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation:  ^2.2.0 
  hydrated_bloc: ^9.1.0
  intl: ^0.17.0
  path_provider: ^2.0.12
  responsive_sizer: ^3.1.1
  

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Spartan
      fonts:
        - asset: fonts/Spartan-Regular.ttf
        - asset: fonts/Spartan-Bold.ttf
          weight: 700